# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):

    def playStopMusic(self):
        print("Play or stop music here")
        print("Change icon to play if its paused")
        print("Change icon to pause if its played")

    def goToLastMusic(self):
        print("Go to last music")
    
    def goToNextMusic(self):
        print("Go to next music")

    def sendYoutubeID(self):
        print("Send Youtube ID")
        print(self.lineEdit.text)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1280, 800)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.labelNaviBar = QtGui.QLabel(self.centralwidget)
        self.labelNaviBar.setGeometry(QtCore.QRect(0, 0, 1280, 48))
        self.labelNaviBar.setText(_fromUtf8(""))
        self.labelNaviBar.setPixmap(QtGui.QPixmap(_fromUtf8("images/navibar.png")))
        self.labelNaviBar.setScaledContents(True)
        self.labelNaviBar.setObjectName(_fromUtf8("labelNaviBar"))
        self.labelPlayB = QtGui.QLabel(self.centralwidget)
        self.labelPlayB.setGeometry(QtCore.QRect(0, 680, 1280, 120))
        self.labelPlayB.setText(_fromUtf8(""))
        self.labelPlayB.setPixmap(QtGui.QPixmap(_fromUtf8("images/playerbackground.png")))
        self.labelPlayB.setScaledContents(True)
        self.labelPlayB.setObjectName(_fromUtf8("labelPlayB"))
        self.labelAlbumPic = QtGui.QLabel(self.centralwidget)
        self.labelAlbumPic.setGeometry(QtCore.QRect(20, 700, 75, 75))
        self.labelAlbumPic.setText(_fromUtf8(""))
        self.labelAlbumPic.setPixmap(QtGui.QPixmap(_fromUtf8("images/albumpic.png")))
        self.labelAlbumPic.setScaledContents(True)
        self.labelAlbumPic.setObjectName(_fromUtf8("labelAlbumPic"))
        self.labelTrack1B = QtGui.QLabel(self.centralwidget)
        self.labelTrack1B.setEnabled(True)
        self.labelTrack1B.setGeometry(QtCore.QRect(20, 288, 1225, 40))
        self.labelTrack1B.setText(_fromUtf8(""))
        self.labelTrack1B.setPixmap(QtGui.QPixmap(_fromUtf8("images/trackname1.png")))
        self.labelTrack1B.setScaledContents(True)
        self.labelTrack1B.setObjectName(_fromUtf8("labelTrack1B"))
        self.labelTrack3B = QtGui.QLabel(self.centralwidget)
        self.labelTrack3B.setGeometry(QtCore.QRect(20, 368, 1225, 40))
        self.labelTrack3B.setText(_fromUtf8(""))
        self.labelTrack3B.setPixmap(QtGui.QPixmap(_fromUtf8("images/trackname1.png")))
        self.labelTrack3B.setScaledContents(True)
        self.labelTrack3B.setObjectName(_fromUtf8("labelTrack3B"))
        self.labelTrack5B = QtGui.QLabel(self.centralwidget)
        self.labelTrack5B.setGeometry(QtCore.QRect(20, 448, 1225, 40))
        self.labelTrack5B.setText(_fromUtf8(""))
        self.labelTrack5B.setPixmap(QtGui.QPixmap(_fromUtf8("images/trackname1.png")))
        self.labelTrack5B.setScaledContents(True)
        self.labelTrack5B.setObjectName(_fromUtf8("labelTrack5B"))
        self.labelTrack7B = QtGui.QLabel(self.centralwidget)
        self.labelTrack7B.setGeometry(QtCore.QRect(20, 528, 1225, 40))
        self.labelTrack7B.setText(_fromUtf8(""))
        self.labelTrack7B.setPixmap(QtGui.QPixmap(_fromUtf8("images/trackname1.png")))
        self.labelTrack7B.setScaledContents(True)
        self.labelTrack7B.setObjectName(_fromUtf8("labelTrack7B"))
        self.labelTrack1 = QtGui.QLabel(self.centralwidget)
        self.labelTrack1.setGeometry(QtCore.QRect(60, 300, 341, 20))
        self.labelTrack1.setObjectName(_fromUtf8("labelTrack1"))
        self.labelTrack3 = QtGui.QLabel(self.centralwidget)
        self.labelTrack3.setGeometry(QtCore.QRect(60, 380, 341, 20))
        self.labelTrack3.setObjectName(_fromUtf8("labelTrack3"))
        self.labelTrack2 = QtGui.QLabel(self.centralwidget)
        self.labelTrack2.setGeometry(QtCore.QRect(60, 340, 341, 20))
        self.labelTrack2.setObjectName(_fromUtf8("labelTrack2"))
        self.labelTrack4 = QtGui.QLabel(self.centralwidget)
        self.labelTrack4.setGeometry(QtCore.QRect(60, 420, 341, 20))
        self.labelTrack4.setObjectName(_fromUtf8("labelTrack4"))
        self.labelTrack6 = QtGui.QLabel(self.centralwidget)
        self.labelTrack6.setGeometry(QtCore.QRect(60, 500, 341, 20))
        self.labelTrack6.setObjectName(_fromUtf8("labelTrack6"))
        self.labelTrack7 = QtGui.QLabel(self.centralwidget)
        self.labelTrack7.setGeometry(QtCore.QRect(60, 540, 341, 20))
        self.labelTrack7.setObjectName(_fromUtf8("labelTrack7"))
        self.labelTrack5 = QtGui.QLabel(self.centralwidget)
        self.labelTrack5.setGeometry(QtCore.QRect(60, 460, 341, 20))
        self.labelTrack5.setObjectName(_fromUtf8("labelTrack5"))
        self.labelHappyEco = QtGui.QLabel(self.centralwidget)
        self.labelHappyEco.setGeometry(QtCore.QRect(874, 182, 53, 53))
        self.labelHappyEco.setText(_fromUtf8(""))
        self.labelHappyEco.setPixmap(QtGui.QPixmap(_fromUtf8("images/happyemo.png")))
        self.labelHappyEco.setScaledContents(True)
        self.labelHappyEco.setObjectName(_fromUtf8("labelHappyEco"))
        self.labelSadEco = QtGui.QLabel(self.centralwidget)
        self.labelSadEco.setGeometry(QtCore.QRect(1192, 182, 53, 53))
        self.labelSadEco.setText(_fromUtf8(""))
        self.labelSadEco.setPixmap(QtGui.QPixmap(_fromUtf8("images/angryemo.png")))
        self.labelSadEco.setScaledContents(True)
        self.labelSadEco.setObjectName(_fromUtf8("labelSadEco"))
        self.labelEmotionBar = QtGui.QLabel(self.centralwidget)
        self.labelEmotionBar.setGeometry(QtCore.QRect(954, 208, 213, 3))
        self.labelEmotionBar.setText(_fromUtf8(""))
        self.labelEmotionBar.setPixmap(QtGui.QPixmap(_fromUtf8("images/emobar.png")))
        self.labelEmotionBar.setScaledContents(True)
        self.labelEmotionBar.setObjectName(_fromUtf8("labelEmotionBar"))
        self.labelUploadB = QtGui.QLabel(self.centralwidget)
        self.labelUploadB.setGeometry(QtCore.QRect(859, 93, 346, 30))
        self.labelUploadB.setText(_fromUtf8(""))
        self.labelUploadB.setPixmap(QtGui.QPixmap(_fromUtf8("images/upload.png")))
        self.labelUploadB.setScaledContents(True)
        self.labelUploadB.setObjectName(_fromUtf8("labelUploadB"))
        self.labelRecord = QtGui.QLabel(self.centralwidget)
        self.labelRecord.setGeometry(QtCore.QRect(1215, 93, 30, 30))
        self.labelRecord.setText(_fromUtf8(""))
        self.labelRecord.setPixmap(QtGui.QPixmap(_fromUtf8("images/record.png")))
        self.labelRecord.setScaledContents(True)
        self.labelRecord.setObjectName(_fromUtf8("labelRecord"))
        self.labelUpload = QtGui.QLabel(self.centralwidget)
        self.labelUpload.setGeometry(QtCore.QRect(970, 103, 131, 16))
        self.labelUpload.setObjectName(_fromUtf8("labelUpload"))
        self.labelPlaying = QtGui.QLabel(self.centralwidget)
        self.labelPlaying.setGeometry(QtCore.QRect(30, 300, 17, 17))
        self.labelPlaying.setText(_fromUtf8(""))
        self.labelPlaying.setPixmap(QtGui.QPixmap(_fromUtf8("images/playing.png")))
        self.labelPlaying.setScaledContents(True)
        self.labelPlaying.setObjectName(_fromUtf8("labelPlaying"))
        self.labelPlayBar = QtGui.QLabel(self.centralwidget)
        self.labelPlayBar.setGeometry(QtCore.QRect(590, 740, 482, 3))
        self.labelPlayBar.setText(_fromUtf8(""))
        self.labelPlayBar.setPixmap(QtGui.QPixmap(_fromUtf8("images/playbar.png")))
        self.labelPlayBar.setScaledContents(True)
        self.labelPlayBar.setObjectName(_fromUtf8("labelPlayBar"))
        self.labelVolume = QtGui.QLabel(self.centralwidget)
        self.labelVolume.setGeometry(QtCore.QRect(1110, 730, 27, 25))
        self.labelVolume.setText(_fromUtf8(""))
        self.labelVolume.setPixmap(QtGui.QPixmap(_fromUtf8("images/volume.png")))
        self.labelVolume.setScaledContents(True)
        self.labelVolume.setObjectName(_fromUtf8("labelVolume"))
        self.labelVolumeBar = QtGui.QLabel(self.centralwidget)
        self.labelVolumeBar.setGeometry(QtCore.QRect(1150, 740, 103, 3))
        self.labelVolumeBar.setText(_fromUtf8(""))
        self.labelVolumeBar.setPixmap(QtGui.QPixmap(_fromUtf8("images/volumebar.png")))
        self.labelVolumeBar.setScaledContents(True)
        self.labelVolumeBar.setObjectName(_fromUtf8("labelVolumeBar"))
        self.playStopButton = QtGui.QPushButton(self.centralwidget)
        self.playStopButton.setGeometry(QtCore.QRect(375, 715, 50, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.playStopButton.setPalette(palette)
        self.playStopButton.setAutoFillBackground(False)
        self.playStopButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playStopButton.setIcon(icon)
        self.playStopButton.setIconSize(QtCore.QSize(50, 50))
        self.playStopButton.setObjectName(_fromUtf8("playStopButton"))
        self.lastButton = QtGui.QPushButton(self.centralwidget)
        self.lastButton.setGeometry(QtCore.QRect(280, 730, 34, 20))
        self.lastButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/last.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lastButton.setIcon(icon1)
        self.lastButton.setIconSize(QtCore.QSize(34, 20))
        self.lastButton.setObjectName(_fromUtf8("lastButton"))
        self.nextButton = QtGui.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(480, 730, 34, 20))
        self.nextButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon2)
        self.nextButton.setIconSize(QtCore.QSize(34, 20))
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(860, 140, 341, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(780, 140, 71, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.okButton = QtGui.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(1205, 135, 51, 41))
        self.okButton.setObjectName(_fromUtf8("okButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.playStopButton.clicked.connect(self.playStopMusic)
        self.lastButton.clicked.connect(self.goToLastMusic)
        self.nextButton.clicked.connect(self.goToNextMusic)
        self.okButton.clicked.connect(self.sendYoutubeID)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelTrack1.setText(_translate("MainWindow", "01 Top of the world        by Imagine Dragons", None))
        self.labelTrack3.setText(_translate("MainWindow", "03 Sail                            by AWOLNATION", None))
        self.labelTrack2.setText(_translate("MainWindow", "02 Girlfriend                   by Avril Lavigne", None))
        self.labelTrack4.setText(_translate("MainWindow", "04 HELP                         by The Beatles", None))
        self.labelTrack6.setText(_translate("MainWindow", "05 Baby                          by Justin Bieber", None))
        self.labelTrack7.setText(_translate("MainWindow", "06 Roar                          by Katy Perry", None))
        self.labelTrack5.setText(_translate("MainWindow", "05 Toxic                          by Britney Spears", None))
        self.labelUpload.setText(_translate("MainWindow", "Upload / Add File Path", None))
        self.label.setText(_translate("MainWindow", "Youtube ID", None))
        self.okButton.setText(_translate("MainWindow", "OK", None))

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

